"""
FastMCP server builder: takes tools generated by tool_builder and registers them
on an in-process FastMCP server. Returned server is wrapped in FastMCPToolset
for the main agent.
"""

from __future__ import annotations

from pathlib import Path

from loguru import logger
from mcp.server.fastmcp import FastMCP

from tool_builder import build_tools


async def build_tool_server(artifacts_root: Path) -> FastMCP | None:
    """Build a FastMCP server with tools generated from the artifact specs."""
    tools = await build_tools(artifacts_root)
    if not tools:
        return None

    server = FastMCP("artifact-tools")
    for spec, fn in tools:
        server.add_tool(fn, name=spec.name, description=spec.description)
        logger.info("[ToolServer] registered: {}", spec.name)

    return server
